import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'fb_clone/login_page.dart' as fb_clone_login;
import 'fb_clone/feed_page.dart' as fb_clone_feed;
import 'fb_clone/profile_page.dart' as fb_clone_profile;
import 'firebase_options.dart'; // This file will be generated by flutterfire

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // We try to initialize with DefaultFirebaseOptions if available, else just init.
  // Note: For Web/Windows, options are usually required.
  // The user will need to generate firebase_options.dart
  try {
     await Firebase.initializeApp(
       options: DefaultFirebaseOptions.currentPlatform,
     );
  } catch (e) {
      // If options file is missing, this might fail or we might try without options
      // But for this task avoiding a crash is better so we can show UI
      print("Firebase init failed (expected if config missing): $e");
      try {
        await Firebase.initializeApp(); 
      } catch (e2) {
         print("Firebase init without options failed: $e2");
      }
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Friendly Social',
      theme: ThemeData(
        primaryColor: const Color(0xFF1877F2),
        useMaterial3: true,
      ),
      routes: {
        '/fb_login': (_) => const fb_clone_login.FBLoginPage(),
        '/fb_feed': (_) => const fb_clone_feed.FBFeedPage(),
        '/fb_profile': (_) => const fb_clone_profile.FBProfilePage(),
      },
      home: const fb_clone_login.FBLoginPage(),
    );
  }
}

class HomePage extends StatelessWidget {
  final String email;
  final String displayName;

  const HomePage({
    super.key,
    required this.email,
    required this.displayName,
  });

  @override
  Widget build(BuildContext context) {
    final fbBlue = const Color(0xFF1877F2);

    return Scaffold(
      appBar: AppBar(
        backgroundColor: fbBlue,
        title: const Text('Home'),
        actions: [
          IconButton(
            icon: const Icon(Icons.person),
            tooltip: 'Profile',
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) => ProfilePage(email: email),
                ),
              );
            },
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              'Welcome back, $displayName 👋',
              style: const TextStyle(fontSize: 18),
            ),
            const SizedBox(height: 18),
            Card(
              elevation: 2,
              child: ListTile(
                leading: const Icon(Icons.person_add, color: Colors.blue),
                title: const Text('Add Friend'),
                subtitle: const Text('Add a new friend to your list'),
                trailing: ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: fbBlue,
                  ),
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (_) => const AddFriendPage(),
                      ),
                    );
                  },
                  child: const Text('Open'),
                ),
              ),
            ),
            const SizedBox(height: 12),
            Card(
              elevation: 2,
              child: ListTile(
                leading: const Icon(Icons.person, color: Colors.green),
                title: const Text('Profile'),
                subtitle: const Text('View or edit your profile'),
                trailing: ElevatedButton(
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (_) => ProfilePage(email: email),
                      ),
                    );
                  },
                  child: const Text('Open'),
                ),
              ),
            ),
            const SizedBox(height: 24),
            ElevatedButton.icon(
              icon: const Icon(Icons.logout),
              label: const Text('Logout'),
              onPressed: () {
                Navigator.pushReplacementNamed(context, '/fb_login');
              },
            ),
          ],
        ),
      ),
    );
  }
}

class AddFriendPage extends StatefulWidget {
  const AddFriendPage({super.key});

  @override
  State<AddFriendPage> createState() => _AddFriendPageState();
}

class _AddFriendPageState extends State<AddFriendPage> {
  final _formKey = GlobalKey<FormState>();
  final _nameCtrl = TextEditingController();
  final _emailCtrl = TextEditingController();

  @override
  void dispose() {
    _nameCtrl.dispose();
    _emailCtrl.dispose();
    super.dispose();
  }

  void _submit() {
    if (_formKey.currentState?.validate() ?? false) {
      final name = _nameCtrl.text.trim();
      final email = _emailCtrl.text.trim();

      final message = email.isEmpty
          ? 'You added $name to your friends.'
          : 'You added $name ($email) to your friends.';

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(message)),
      );

      _nameCtrl.clear();
      _emailCtrl.clear();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add Friend')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _nameCtrl,
                decoration: const InputDecoration(labelText: 'Full name'),
                validator: (v) =>
                    v == null || v.trim().isEmpty ? 'Enter a name' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _emailCtrl,
                keyboardType: TextInputType.emailAddress,
                decoration: const InputDecoration(
                  labelText: 'Email (optional)',
                ),
                validator: (v) {
                  if (v == null || v.trim().isEmpty) return null;
                  final valid = RegExp(
                    r'^[^@\s]+@[^@\s]+\.[^@\s]+$',
                  ).hasMatch(v);
                  return valid ? null : 'Enter a valid email';
                },
              ),
              const SizedBox(height: 18),
              ElevatedButton(
                onPressed: _submit,
                child: const Text('Add'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class ProfilePage extends StatefulWidget {
  final String email;

  const ProfilePage({
    super.key,
    required this.email,
  });

  @override
  State<ProfilePage> createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage> {
  late TextEditingController _nameCtrl;
  late TextEditingController _bioCtrl;

  @override
  void initState() {
    super.initState();
    _nameCtrl = TextEditingController(text: 'User');
    _bioCtrl = TextEditingController(text: 'This is my profile.');
  }

  @override
  void dispose() {
    _nameCtrl.dispose();
    _bioCtrl.dispose();
    super.dispose();
  }

  void _save() {
    final name = _nameCtrl.text.trim();
    final who = name.isEmpty ? 'Profile' : name;

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text('Profile saved — thanks, $who!')),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Profile')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            TextFormField(
              controller: _nameCtrl,
              decoration: const InputDecoration(labelText: 'Display name'),
            ),
            const SizedBox(height: 12),
            TextFormField(
              readOnly: true,
              controller: TextEditingController(text: widget.email),
              decoration: const InputDecoration(labelText: 'Email'),
            ),
            const SizedBox(height: 12),
            TextFormField(
              controller: _bioCtrl,
              maxLines: 3,
              decoration: const InputDecoration(labelText: 'Bio'),
            ),
            const SizedBox(height: 18),
            ElevatedButton(
              onPressed: _save,
              child: const Text('Save'),
            ),
          ],
        ),
      ),
    );
  }
}
